In [1]:
import math
from torch import empty

from generate_data import generate_data
from Modules import Sequential, Linear, ReLU, Tanh, Sigmoid

In [2]:
N = 1000

train_input, train_target, test_input, test_target = generate_data(1000, True)

print(train_input.shape)
print(train_input.std())
print(train_input.mean())

torch.Size([1000, 2])
tensor(1.)
tensor(-1.3383e-07)


In [3]:
r = ReLU()
print(r.forward(train_input))
print(r.backward(test_input))
print(r.param())

tensor([[0.9497, -0.0000],
        [-0.0000, -0.0000],
        [1.3456, 0.1700],
        ...,
        [0.0635, 1.3008],
        [1.6612, 0.9951],
        [1.0979, -0.0000]])
tensor([[-0.4122, -0.0000],
        [-0.0000, -0.0000],
        [ 1.6260, -1.6718],
        ...,
        [-0.6255, -0.7552],
        [ 0.7357, -0.7366],
        [-0.2294, -0.0000]])
ReLU has no parameters
None


In [4]:
t = Tanh()
print(t.forward(train_input))
print(t.backward(test_input))
print(t.param())

tensor([[ 0.7397, -0.8240],
        [-0.8019, -0.8752],
        [ 0.8730,  0.1683],
        ...,
        [ 0.0635,  0.8619],
        [ 0.9304,  0.7595],
        [ 0.7997, -0.2692]])
tensor([[-0.1867, -0.2801],
        [-0.3031, -0.3822],
        [ 0.3867, -1.6245],
        ...,
        [-0.6230, -0.1941],
        [ 0.0989, -0.3117],
        [-0.0827, -0.9158]])
Tanh has no parameters
None


In [5]:
s = Sigmoid()
print(s.forward(train_input))
print(s.backward(test_input))
print(s.param())

tensor([[0.7211, 0.2370],
        [0.2490, 0.2051],
        [0.7934, 0.5424],
        ...,
        [0.5159, 0.7860],
        [0.8404, 0.7301],
        [0.7499, 0.4314]])
tensor([[-0.0829, -0.1578],
        [-0.1588, -0.2662],
        [ 0.2665, -0.4150],
        ...,
        [-0.1562, -0.1270],
        [ 0.0987, -0.1452],
        [-0.0430, -0.2422]])
Sigmoid has no parameters
None


In [6]:
l = Linear(2, 3)

print(l.forward(empty(2).normal_()))
print(l.backward(empty(3).normal_()))
l.param()

tensor([ 4.0844e-01,  2.6811e+00, -1.0228e+11])
tensor([1.6715, 0.0437])


[(tensor([[ 0.6341,  0.1745],
          [ 2.4289,  2.1635],
          [-1.5185,  1.2460]]), tensor([[ 0.9817,  1.6720],
          [-0.0148, -0.0252],
          [-0.0964, -0.1642]])),
 (tensor([ 0.0000e+00,  0.0000e+00, -1.0228e+11]),
  tensor([ 2.2386, -0.0338, -0.2199]))]

In [27]:
l1 = Linear(4,6)
r1 = ReLU()
l2 = Linear(6, 8)
t2 = Tanh()

S = Sequential(l1, r1, l2, t2)
print(S.forward(empty(4).normal_()))
print(S.backward(empty(8).normal_()))
print(S.param())
S.name

tensor([-0.4584,  0.9998, -0.9819,  1.0000,  1.0000,  1.0000,  0.9944,  1.0000])
tensor([-0.3121, -0.9346, -0.3514, -1.6374])
ReLU has no parameters
Tanh has no parameters
[[(tensor([[-0.8555,  0.3907, -0.8390, -0.6090],
        [-1.2687, -2.2299,  1.2594, -0.5788],
        [ 0.0683,  0.2891, -0.6697,  0.1074],
        [-0.1166,  0.7556,  0.2356,  0.2668],
        [ 0.1682,  1.4267,  0.1849, -0.5607],
        [ 0.4286,  1.3842, -0.8861,  1.4453]]), tensor([[ 0.3568,  0.8239, -0.2503, -0.5055],
        [-0.0000, -0.0000,  0.0000,  0.0000],
        [-0.0353, -0.0816,  0.0248,  0.0501],
        [-1.2342, -2.8501,  0.8660,  1.7488],
        [ 0.3698,  0.8541, -0.2595, -0.5241],
        [-0.2804, -0.6474,  0.1967,  0.3973]])), (tensor([1.0000e+00, 1.0000e+00, 3.3631e-44, 0.0000e+00, 1.4013e-45, 0.0000e+00]), tensor([ 0.5023, -0.0000, -0.0497, -1.7378,  0.5208, -0.3948]))], None, [(tensor([[-0.4549,  0.4885,  0.0560,  1.7629, -0.5356,  0.3928],
        [-1.0614, -0.7142, -0.0041,  0.5563,  0

'Linear(4x6) => ReLU => Linear(6x8) => Tanh'